# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N78WLUWIg3sxIZ6xjDVmjTTrYjtWK8QX

# Question 1 :
Define a function which can compute the sum of two numbers.

Hints:
Define a function with two numbers as arguments. You can compute the sum in the function and return the value.
"""

def sumtwo(number1, number2):
    return number1+number2
print (sumtwo(1,2))

"""# Question 2:

    Write a method which can calculate square value of number

Hints:
    Using the ** operator

"""

number = float(input(" Please Enter any numeric Value : "))

square = number ** 2

print("The Square of a Given Number {0}  = {1}".format(number, square))

"""# Question 3
Define a function that can convert a integer into a string and print it in console.

Hints:

Use str() to convert a number to string.
"""

num = 15
print(type(num))
converted_num = str(num)
print(type(converted_num))

"""# Question 4 :
Define a function that can receive two integral numbers in string form and compute their sum and then print it in console.

Hints:

Use int() to convert a string to integer.
"""

def calculateSum (a,b):
    s = int(a) + int(b)
    return s 
num1 = "17"
num2 = "12"
sum = calculateSum (num1, num2)
print ("Sum = ", sum)

"""# Question 5 :
Define a function that can accept two strings as input and concatenate them and then print it in console.

Hints:

Use + to concatenate the strings
"""

st1 = input('Please enter the first string:\n')
st2 = input('Please enter the second string:\n')

print('Concatenated String =', st1 + st2)

"""# Question 6 :
Define a function that can accept two strings as input and print the string with maximum length in console. If two strings have the same length, then the function should print al l strings line by line.

Hints:

Use len() function to get the length of a string
"""

def printValue(s1,s2):
    len1 = len(s1)
    len2 = len(s2)
    if len1 > len2:
        print(s1)
    elif len2 > len1:
        print(s2) 
    else:
        print(s1)
        print(s2)


s1,s2=input("please enter string")
printVal(s1,s2)

"""# Question 7 :
Define a function that can accept an integer number as input and print the "It is an even number" if the number is even, otherwise print "It is an odd number".

Hints:

Use % operator to check if a number is even or odd.
"""

def printValue(s1,s2):
    len1 = len(s1)
    len2 = len(s2)
    if len1 > len2:
        print(s1)
    elif len2 > len1:
        print(s2) 
    else:
        print(s1)
        print(s2)


s1,s2=input("please enter string")
printVal(s1,s2)

"""# Question 8 :
Write a program which accepts a string as input to print "Yes" if the string is "yes" or "YES" or "Yes", otherwise print "No". 

Hints:

Use if statement to judge condition.
"""

Join = "yes"
if Join=='yes' or Join =='Yes':
  print("successfully joined")
else:
  print ("Sorry for asking...")

"""# Question 9 :
Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5,
between 2000 and 3200 (both included).
The numbers obtained should be printed in a comma-separated sequence on a single line.

Hints: 
Consider use range(#begin, #end) method
"""

#Search about it please
value = int(input("Enter value: "))
def fact(x):
    if x == 0:
        return 1
    return x * fact(x - 1)
fact(value)

"""# Question 10 :
Write a program which can compute the factorial of a given numbers.
The results should be printed in a comma-separated sequence on a single line.
Suppose the following input is supplied to the program:
8
Then, the output should be:
40320

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
"""

#Search about it please
value = int(input("Enter value: "))
def fact(x):
    if x == 0:
        return 1
    return x * fact(x - 1)
fact(value)

"""# Question 11 :
Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.
Suppose the following input is supplied to the program:
9
Then, the output should be:
11106

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.

"""

value = input("Enter value: ")

n1 = value * 1
n2 = value * 2
n3 = value * 3
n4 = value * 4

total = int(n1) + int(n2) + int(n3) + int(n4)
print(total)