# -*- coding: utf-8 -*-
"""Copy of sprint 1 task4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FegH3mmoqP9s-Tk9eCiju0PeVgr3Sv1H

# 1- Question 
1-read you csv file (https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv )

2-print the first 5 rows 

3-print the shape of the data

4- print and data type of each column
"""

import pandas as pd
data = pd.read_csv ('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Shape of the data:")
print(data.shape)
print("\nData Type:")
print(type(data))
print("\nFirst 5 rows:")
print(data.head())

"""# 2-Question
1- print carat column

2- Write a Pandas program to create a new 'Quality -color' Column (cut,color)

examble => ( Ideal, E)
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
#print(diamonds['carat'])
diamonds['Quality–color'] = diamonds.cut + ', ' + diamonds.color
print(diamonds.head())

"""# 3-Question
1-Write a Pandas program to summarize the data.

2- only one column => 'table'

3- only 'float64' columns of the diamonds Dataframe. => include=['...']
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Summarize of 'object' columns:")
print(diamonds.describe(include=['object']))

"""# 4-Question
Write a Pandas program to find the details of the diamonds where length>5, width>5 and depth>5. (x,y,z)
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Original Dataframe:")
print(diamonds.head())
print("\nDiamonds where length>5, width>5 and depth>5:")
result = diamonds[(diamonds.x>5) & (diamonds.y>5) & (diamonds.z>5)]
print(result.head())

"""# 5-Question
1- rename one col

2- rename two col togeather

3- rename all col togeather
"""

import pandas as pd
diamonds =pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Original dataframe: ")
print(diamonds.head())
print("after renaming two of the columnsof said dataframe:" ) 
diamonds.rename(columns={'color':'diamond_color','calarity':'diamond_clarity'})
print(diamonds.head())
diamonds_cols=['new_carat','new_cut','new_color','new_clarity','new_depth','new_table','new_price','new_x','new_y','new_z']
print("after renaming all the columns of said dataframe:" ) 
print(diamonds.head())

"""# 6-Question
Write a Pandas program to find the diamonds that are either Good or Very Good.
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Original Dataframe:")
print(diamonds.head())
print("\nDiamonds that are either Good or Very Good:")
result = diamonds[(diamonds.cut == 'Good') | (diamonds.cut == 'Very Good')]
print(result.head())

"""# 7-Question
1-print the name of all the columns

2- Mean of each column

3-Mean of each row of diamonds DataFrame:
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')

print("Original Dataframe:")
print(diamonds.head())
print("\nMean of each row of diamonds DataFrame:")
print(diamonds.mean(axis=1).head())

"""# 8-Question
1- mean of 'price' column only

2- Write a Pandas program to calculate the mean of price for each cut of diamonds DataFrame.

3-Write a Pandas program to calculate count, minimum, maximum price for each cut of diamonds DataFrame.

4- count how many times each value in cut series of diamonds DataFrame occurs. value_counts()
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Original Dataframe:")
print(diamonds.head())
print(diamonds.groupby('cut').price.mean())
print("\nCount, minimum, maximum  price for each cut of diamonds DataFrame:")
print(diamonds.groupby('cut').price.agg(['count', 'min', 'max']))
print(diamonds.cut.value_counts())

"""# 9-Question
Write a Pandas program to count the number of missing values in each Series of diamonds DataFrame.
"""

import pandas as pd
diamonds = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/diamonds.csv')
print("Original Dataframe:")
print(diamonds.head())
print("\nNumber of missing values in each Series of diamonds DataFrame:")
print(diamonds.isnull().sum())