# -*- coding: utf-8 -*-
"""sprint1 task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qcj6adpyMP1YaXPQXBn2tx0EeXPuch8w

# Question 1:
Define a function which can print a dictionary where the keys are numbers between 1 and 3 (both included) and the values are square of keys.

Hints:

Use dict[key]=value pattern to put entry into a dictionary.
Use ** operator to get power of a number
"""

md=dict() 
for x in range(1,3):
      md[x]=x**2
print(md)

"""# Question 2:
Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the values only.

Hints:

Use dict[key]=value pattern to put entry into a dictionary.
Use ** operator to get power of a number.
Use range() for loops.
Use keys() to iterate keys in the dictionary. Also we can use item() to get key/value pairs.
"""

md=dict()
for x in range(1,20):
     md[x]=x**2
print(md)

"""# Question 3:
Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the keys only.

Hints:

Use dict[key]=value pattern to put entry into a dictionary.
Use ** operator to get power of a number.
Use range() for loops.
Use keys() to iterate keys in the dictionary. Also we can use item() to get key/value pairs.
"""

def printDict():
        dict={i:i**2 for i in range (1,20)}
        print (dict)
        printDict()

"""# Question 4 
Write a Python program to check a dictionary is empty or not
"""

my_dict = {}

if not bool(my_dict):
     print('dictionary is empty')

"""# Question 5

Write a Python program to test whether every element in s is in t and every element in t is in s.
"""

def symmetric_difference(s,t):
    s = [3,5,7,9]
    t = [3,5,7,9]
    s = s.symmetric_difference(t)

print(s)

"""# Question 6
Create set 1 and set 2 then 
Write a Python program to 1- create an intersection of sets.
2-  a union of sets.
3- create set difference.
4- a symmetric difference.

"""

set1 = {1,2,2,3,4,5,5,6}
set2 = {1,3,3,4,5,7,9,10}
print("intersection:",set1 & set2)
print("union:",set1|set2   )
print("difference:",set1 - set2)
print("symmetric",set1^set2 )

"""# Question  7
Write a Python program to use of frozensets.
"""

k = [1,2,3,5,4]
fset = frozenset(k)
print (fset)

"""# Question 8
Write a Python program to find maximum and the minimum value in a set.
"""

def set(n, min, max):

    if n < min:
        return min
    elif n > max:
        return max
    else:
        return n

"""# Question9 :
With a given tuple (1,2,3,4,5,6,7,8,9,10), write a program to print the first half values in one line and the last half values in one line. 

Hints:

Use [n1:n2] notation to get a slice from a tuple.

"""

tp = (1,2,3,4,5,6,7,8,9,10)
n1 = tp[:5]
n2 = tp[5:]
print (n1)
print (n2)

"""# Question 10 :
You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
1: Sort based on name;
2: Then sort based on age;
3: Then sort by score.
The priority is that name > age > score.
If the following tuples are given as input to the program:
Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]

Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
We use itemgetter to enable multiple sort keys.

Solutions:
from operator import itemgetter, attrgetter
"""

from operator import itemgetter, attrgetter
itemlist=[('Tom,19,80'), ('John,20,90'), ('Jony,17,91'), ('Jony,17,93') ,('Json,21,85') ]
print(sorted(itemlist))

"""# Question 11:

Please write a program to generate a list with 5 random numbers between 100 and 200 inclusive.



Hints:
Use random.sample() to generate a list of random values.
"""

import random
mylist = []
for i in range(0,5):
    x = random.randint(100,200)
    mylist.append(x)

print(mylist)

"""# Question 12
Please write a program to randomly generate a list with 5 even numbers between 100 and 200 inclusive.

Hints:
Use random.sample() to generate a list of random values.
"""

import random
mylist = []
for i in range(0,10):
    i = random.randint(100,200)
    if(i%2==0):
        mylist.append(i)
        print(mylist)
    else :
        pass

"""# Question 13
Please write a program to randomly print a integer number between 7 and 15 inclusive.

Hints: Use random.randrange() to a random integer in a given range.
"""

import random
mylist = []
for i in range(0,10):
    p= random.randint(7,15)
    mylist.append(p)
print(mylist)

"""# Question 14

Please write a program to print the running time of execution of "1+1" for 100 times.
Hints:
Use timeit() function to measure the running time.
"""

import timeit
print("The time taken is ",timeit.timeit(stmt='a=1;b=1;sum=a+b')*100)

"""# Question 15 :

Please write a program to shuffle and print the list [3,6,7,8].

Hints:
Use shuffle() function to shuffle a list.
"""

import random

mylist = [3,6,7,8]
random.shuffle(mylist)

print(mylist)